### ISSUE TITLE
Wrong command to restart nfs

### ISSUE THREAD

**Issue by ghost** [skx/Buffalo-220-NAS#1]
The commands indicated are "/opt/etc/init.d/*nsfs* stop"  and "/opt/etc/init.d/*nsfs* start". I think they should be "/opt/etc/init.d/*nfs* stop"  and "/opt/etc/init.d/*nfs* start".

**Comment by skx** [comment]
I don't have it to hand, any longer, so I cannot confirm.  It might be a typo, or it might not!  I'll correct !
