### ISSUE TITLE
nfs-server mounting problems

### ISSUE THREAD

**Issue by ghost** [skx/Buffalo-220-NAS#2]
When mounting nfs shared folders I cannot stat files that exceed 2.0 Gb. I have tried to use nfs-utils but I wasn't able to mount the shares. I've installed package unfs3 and even if the package is not recommended it worked fine with my raspberry running dietpi and my ubuntu 18.04.

**Comment by skx** [comment]
The 2GB size limit is a limitation of NFS v2.0.

In order to exceed that size you need to have both NFS server and NFS client(s) running version 3 or higher.  But I think this issue is outside the scope of this project - which is mostly to document how to get root, and play.

**Comment by ghost** [comment]
Thank you very much. Your guide has been very useful to me. I agree with you that the NFS is out of scope. However I've really enjoyed the possibility to ssh to my nas. Thank you again.
